import Link from "next/link";
import { Boxes, ChevronLeft, ChevronRight, Search } from "lucide-react";
import { ProductActions } from "@/features/products/components/product-actions";
import { ProductFormDialog } from "@/features/products/components/product-form-dialog";
import { ProductImage } from "@/features/products/components/product-image";
import { getProductPage } from "@/features/products/queries/get-products";
import { requireUser } from "@/lib/auth/guards";
import { formatRupiah } from "@/lib/utils";

type SearchParams = Promise<{ q?: string; category?: string; status?: string; page?: string }>;

function pageHref(params: { q: string; category: string; status: string }, page: number) {
  const search = new URLSearchParams();
  if (params.q) search.set("q", params.q);
  if (params.category) search.set("category", params.category);
  if (params.status) search.set("status", params.status);
  search.set("page", String(page));
  return `/products?${search.toString()}`;
}

export default async function ProductsPage({ searchParams }: { searchParams: SearchParams }) {
  const [user, params] = await Promise.all([requireUser(), searchParams]);
  const q = typeof params.q === "string" ? params.q.slice(0, 120) : "";
  const category = typeof params.category === "string" ? params.category.slice(0, 30) : "";
  const status = params.status === "active" || params.status === "inactive" ? params.status : "";
  const requestedPage = Number.parseInt(params.page ?? "1", 10);
  const data = await getProductPage({ search: q, categoryId: category || undefined, status: status || undefined, page: Number.isFinite(requestedPage) ? requestedPage : 1 });
  const filters = { q, category, status };

  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mb-1 text-sm font-medium text-emerald-700">Master data</p><h1 className="text-2xl font-bold tracking-tight text-slate-900">Produk</h1><p className="mt-1 text-sm text-slate-500">Kelola katalog, harga, dan stok produk warung.</p></div>{user.role === "ADMIN" && <ProductFormDialog categories={data.categories} />}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm shadow-slate-100"><div className="border-b border-slate-100 p-4"><div className="mb-4"><h2 className="font-semibold text-slate-900">Daftar produk</h2><p className="mt-1 text-xs text-slate-400">{data.total} produk · halaman {data.page} dari {data.pageCount}</p></div><form method="get" className="grid gap-2 sm:grid-cols-[minmax(200px,1fr)_190px_160px_auto]"><div className="relative"><Search size={16} className="absolute left-3 top-2.5 text-slate-400" /><input name="q" defaultValue={q} maxLength={120} placeholder="Cari nama atau SKU..." className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" /></div><select aria-label="Filter kategori" name="category" defaultValue={category} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:border-emerald-600"><option value="">Semua kategori</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filter status" name="status" defaultValue={status} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:border-emerald-600"><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">Terapkan</button></form></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3 font-semibold">Produk</th><th className="px-5 py-3 font-semibold">Kategori</th><th className="px-5 py-3 text-right font-semibold">Harga</th><th className="px-5 py-3 text-right font-semibold">Stok</th><th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 font-semibold">Dibuat</th>{user.role === "ADMIN" && <th className="px-5 py-3 text-right font-semibold">Aksi</th>}</tr></thead><tbody className="divide-y divide-slate-100">{data.products.length ? data.products.map((product) => <tr key={product.id} className="hover:bg-slate-50/70"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><ProductImage src={product.imageUrl} name={product.name} /><div className="min-w-0"><p className="max-w-[250px] truncate font-semibold text-slate-800">{product.name}</p><p className="mt-0.5 text-xs text-slate-400">SKU {product.sku}</p></div></div></td><td className="px-5 py-4 text-slate-600">{product.category.name}</td><td className="px-5 py-4 text-right font-semibold text-slate-800">{formatRupiah(product.price.toString())}</td><td className="px-5 py-4 text-right text-slate-600">{product.stock}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${product.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{product.isActive ? "Aktif" : "Nonaktif"}</span></td><td className="px-5 py-4 text-slate-500">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeZone: "Asia/Jakarta" }).format(product.createdAt)}</td>{user.role === "ADMIN" && <td className="px-5 py-4"><ProductActions product={{ id: product.id, name: product.name, description: product.description, categoryId: product.categoryId, price: product.price.toString(), stock: product.stock, imageUrl: product.imageUrl, isActive: product.isActive }} categories={data.categories} /></td>}</tr>) : <tr><td colSpan={user.role === "ADMIN" ? 7 : 6} className="px-5 py-14 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-slate-50 text-slate-400"><Boxes size={21} /></div><p className="mt-3 font-semibold text-slate-700">{q || category || status ? "Produk tidak ditemukan" : "Belum ada produk"}</p><p className="mt-1 text-sm text-slate-400">{q || category || status ? "Ubah kata pencarian atau filter lalu coba lagi." : data.categories.length ? "Tambahkan produk agar siap ditawarkan di kasir." : "Buat kategori terlebih dahulu sebelum menambahkan produk."}</p></td></tr>}</tbody></table></div>
      {data.total > data.pageSize && <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3"><p className="text-xs text-slate-500">Menampilkan {Math.min((data.page - 1) * data.pageSize + 1, data.total)}–{Math.min(data.page * data.pageSize, data.total)} dari {data.total}</p><div className="flex gap-2"><Link aria-disabled={data.page <= 1} tabIndex={data.page <= 1 ? -1 : undefined} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${data.page <= 1 ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`} href={pageHref(filters, Math.max(1, data.page - 1))}><ChevronLeft size={15} />Sebelumnya</Link><Link aria-disabled={data.page >= data.pageCount} tabIndex={data.page >= data.pageCount ? -1 : undefined} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${data.page >= data.pageCount ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`} href={pageHref(filters, Math.min(data.pageCount, data.page + 1))}>Berikutnya<ChevronRight size={15} /></Link></div></div>}
    </section>
  </div>;
}
