import Link from "next/link";
import { ChevronLeft, ChevronRight, ReceiptText, Search } from "lucide-react";
import { getTransactionCashiers, getTransactionPage } from "@/features/pos/queries/get-transactions";
import { requireUser } from "@/lib/auth/guards";
import { formatRupiah } from "@/lib/utils";

type SearchParams = Promise<{ q?: string; from?: string; to?: string; page?: string; cashier?: string; payment?: string; status?: string }>;

const paymentLabels: Record<string, string> = { CASH: "Tunai", DEBIT: "Kartu debit", CREDIT: "Kartu kredit", QRIS: "QRIS", TRANSFER: "Transfer" };

function href(params: { q: string; from: string; to: string; cashier: string; payment: string; status: string }, page: number) {
  const query = new URLSearchParams();
  if (params.q) query.set("q", params.q);
  if (params.from) query.set("from", params.from);
  if (params.to) query.set("to", params.to);
  if (params.cashier) query.set("cashier", params.cashier);
  if (params.payment) query.set("payment", params.payment);
  if (params.status) query.set("status", params.status);
  query.set("page", String(page));
  return `/transactions?${query}`;
}

export default async function TransactionsPage({ searchParams }: { searchParams: SearchParams }) {
  await requireUser();
  const params = await searchParams;
  const filters = { q: typeof params.q === "string" ? params.q.slice(0, 40) : "", from: typeof params.from === "string" ? params.from : "", to: typeof params.to === "string" ? params.to : "", cashier: typeof params.cashier === "string" ? params.cashier : "", payment: typeof params.payment === "string" ? params.payment : "", status: typeof params.status === "string" ? params.status : "COMPLETED" };
  const requestedPage = Number.parseInt(params.page ?? "1", 10);
  const [data, cashiers] = await Promise.all([
    getTransactionPage({ search: filters.q, from: filters.from, to: filters.to, cashierId: filters.cashier, paymentMethod: filters.payment, status: filters.status, page: Number.isFinite(requestedPage) ? requestedPage : 1 }),
    getTransactionCashiers()
  ]);
  return <div className="space-y-6">
    <div><p className="mb-1 text-sm font-medium text-emerald-700">Riwayat</p><h1 className="text-2xl font-bold tracking-tight text-slate-900">Transaksi</h1><p className="mt-1 text-sm text-slate-500">Transaksi yang sudah selesai dan tidak dapat diubah.</p></div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm shadow-slate-100"><div className="border-b border-slate-100 p-4"><div className="mb-4"><h2 className="font-semibold text-slate-900">Riwayat transaksi</h2><p className="mt-1 text-xs text-slate-400">{data.total} transaksi ditemukan · halaman {data.page} dari {data.pageCount} · default hanya selesai</p></div><form method="get" className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><div className="relative"><Search size={16} className="absolute left-3 top-2.5 text-slate-400" /><input name="q" defaultValue={filters.q} placeholder="Cari nomor transaksi..." maxLength={40} className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-emerald-600" /></div><input aria-label="Dari tanggal" type="date" name="from" defaultValue={filters.from} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600" /><input aria-label="Sampai tanggal" type="date" name="to" defaultValue={filters.to} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600" /><select aria-label="Kasir" name="cashier" defaultValue={filters.cashier} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600"><option value="">Semua kasir</option>{cashiers.map((cashier) => <option key={cashier.id} value={cashier.id}>{cashier.name}</option>)}</select><select aria-label="Metode pembayaran" name="payment" defaultValue={filters.payment} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600"><option value="">Semua pembayaran</option>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Status transaksi" name="status" defaultValue={filters.status} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600"><option value="COMPLETED">Selesai</option><option value="VOIDED">Void</option><option value="ALL">Semua status</option></select><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3 font-semibold">Nomor transaksi</th><th className="px-5 py-3 font-semibold">Tanggal / waktu</th><th className="px-5 py-3 font-semibold">Kasir</th><th className="px-5 py-3 font-semibold">Item</th><th className="px-5 py-3 font-semibold">Pembayaran</th><th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 text-right font-semibold">Total</th><th className="px-5 py-3 text-right font-semibold">Detail</th></tr></thead><tbody className="divide-y divide-slate-100">{data.transactions.length ? data.transactions.map((transaction) => <tr key={transaction.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 font-semibold text-slate-800">{transaction.invoiceNumber}</td><td className="px-5 py-4 text-slate-500">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(transaction.createdAt)}</td><td className="px-5 py-4 text-slate-600">{transaction.user.name}</td><td className="px-5 py-4 text-slate-600">{transaction.items.reduce((sum, item) => sum + item.quantity, 0)} item</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{paymentLabels[transaction.paymentMethod] ?? transaction.paymentMethod}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${transaction.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{transaction.status === "COMPLETED" ? "Selesai" : "Void"}</span></td><td className="px-5 py-4 text-right font-semibold text-slate-800">{formatRupiah(transaction.total.toString())}</td><td className="px-5 py-4 text-right">{transaction.status === "COMPLETED" ? <Link href={`/transactions/${transaction.id}`} className="text-xs font-semibold text-emerald-700 hover:underline">Lihat detail</Link> : <span className="text-xs text-slate-400">—</span>}</td></tr>) : <tr><td colSpan={8} className="px-5 py-14 text-center"><ReceiptText className="mx-auto text-slate-300" size={28} /><p className="mt-3 font-semibold text-slate-700">{filters.q || filters.from || filters.to || filters.cashier || filters.payment || filters.status !== "COMPLETED" ? "Transaksi tidak ditemukan" : "Belum ada transaksi"}</p><p className="mt-1 text-sm text-slate-400">Transaksi yang sesuai filter akan tampil di sini.</p></td></tr>}</tbody></table></div>
      {data.total > data.pageSize && <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3"><p className="text-xs text-slate-500">{Math.min((data.page - 1) * data.pageSize + 1, data.total)}–{Math.min(data.page * data.pageSize, data.total)} dari {data.total}</p><div className="flex gap-2"><Link href={href(filters, Math.max(1, data.page - 1))} aria-disabled={data.page <= 1} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${data.page <= 1 ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-600"}`}><ChevronLeft size={15} />Sebelumnya</Link><Link href={href(filters, Math.min(data.pageCount, data.page + 1))} aria-disabled={data.page >= data.pageCount} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${data.page >= data.pageCount ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-600"}`}>Berikutnya<ChevronRight size={15} /></Link></div></div>}
    </section>
  </div>;
}
